name: Deployment

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init Vars
        id: init
        run: |
          echo "Ref => ${{github.ref}}"
          echo "PR => ${{github.event.pull_request.number}}"

          if [[ "${{github.ref}}" == "refs/heads/master" ]]; then
              echo "IS_MAIN=true" >> $GITHUB_OUTPUT
          else
              echo "IS_MAIN=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          version: 8.3.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Perform build
        run: pnpm run build

      - name: Deploy production
        if: steps.init.outputs.IS_MAIN == 'true'
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'prod-wibu.surge.sh'
          project: 'dist'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}

      - name: Deploy preview domain
        if: steps.init.outputs.IS_MAIN == 'false'
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'preview-wibu-${{ github.event.pull_request.number }}.surge.sh'
          project: 'dist'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}

      - name: Deployment Production Summary
        if: steps.init.outputs.IS_MAIN == 'true'
        run: echo '🚀 Your domain available in https://prod-wibu.surge.sh' >> $GITHUB_STEP_SUMMARY

      - name: Deployment Preview Summary
        if: steps.init.outputs.IS_MAIN == 'false'
        run: echo '🚀 Your domain available in https://preview-wibu-${{ github.event.pull_request.number }}.surge.sh' >> $GITHUB_STEP_SUMMARY

      - name: Deployment Preview Comment
        if: steps.init.outputs.IS_MAIN == 'false'
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          message: |
            🚀 Your domain available in https://preview-wibu-${{ github.event.pull_request.number }}.surge.sh
          pr_number: ${{ github.event.pull_request.number }}
